version: "3.8"

services:
    mysql:
        image: mysql:8.0
        container_name: cardealership-mysql
        restart: unless-stopped
        environment:
            MYSQL_ROOT_PASSWORD: rootpassword
            MYSQL_DATABASE: cardealership
            MYSQL_USER: root
            MYSQL_PASSWORD: root
        ports:
            - "3306:3306"
        volumes:
            - mysql_data:/var/lib/mysql
            - ./docker/mysql/init:/docker-entrypoint-initdb.d
        command: --default-authentication-plugin=mysql_native_password

volumes:
    mysql_data:
